locations = [
    {'Name': '105 Shuttle', 'Destination': '\nWestlands, Kabete, Uthiru, Kikuyu', 'Fare': '\n40-100',
     'Location': '\nAlong Tom Mboya Street\nNext to Lazarus Restaurant', 'Latitude': -1.2834509, 'Longitude': 36.824989},
    {'Name': '2NK Sacco | (Nyeri, Karatina)', 'Destination': '\nNyeri, Karatina',
     'Fare': '\nNyeri: Ksh. 500\nKaratina: Ksh. 450',
     'Location': '\nAccra Rd\nNear Accra Trade Centre', 'Latitude': -1.282933,
     'Longitude': 36.827154},
    {'Name': '2NK Sacco | (Nanyuki, Mukurwe-ini)',
     'Destination': '\nNanyuki', 'Fare': '\nNanyuki: Ksh. 650\nMukurwe-ini: Ksh.',
     'Location': '\nAccra Rd\nNear Accra Trade Centre', 'Latitude': -1.282804,
     'Longitude': 36.827160},
    {'Name': '2NK Sacco | (Kerugoya, Muranga)', 'Destination': '\nKerugoya, Muranga',
     'Fare': '\nKerugoya: Ksh.\nMuranga: Ksh.',
     'Location': '\nAccra Rd\nNear Accra Trade Centre', 'Latitude': -1.282728,
     'Longitude': 36.827283},
    {'Name': '2NK Sacco | (Nakuru)', 'Destination': '\nNakuru', 'Fare': '\nNakuru: Ksh. 600',
     'Location': '\nTea Room Stage\nRiver Road-Accra Road Junction', 'Latitude': -1.282653,
     'Longitude': 36.827481},
    {'Name': '4NTE Sacco', 'Destination': '\nNanyuki, Isiolo, Nakuru, Eldoret',
     'Fare': '\nNanyuki-Isiolo: Ksh. 600\nNakuru: Ksh. 500\nEldoret: Ksh. 1000',
     'Location': '\nAccra Road\nNear Scorpio Business Centre', 'Latitude': -1.283124,
     'Longitude': 36.826953},
    {'Name': 'Airbus Shuttle | UNIQUE Shuttle | Meru Nissan Sacco', 'Destination': '\nChuka, Meru, (Airbus),'
     '\nTharaka University, Meru, (UNIQUE),\nChuka, Chogoria, Meru, (Meru Nissan Sacco)',
     'Fare': '\nAirbus & UNIQUE Shuttles\nPeak: Ksh. 1000\nOffPeak: Ksh. 900\n\nMeru Nissan Sacco\nKsh. 700',
     'Location': '\nAccra Road\nNear Nyota Building',
     'Latitude': -1.283090, 'Longitude': 36.826894},
    {'Name': 'BDT Sacco', 'Destination': '\nBaba Dogo',
     'Fare': '\nKsh. 60',
     'Location': '\nLagos Road-Tom Mboya Street Junction',
     'Latitude': -1.282119, 'Longitude': 36.823485},
    {'Name': 'Bybus Trans', 'Destination': '\nMP.SHH, Parklands, Westlands',
     'Fare': '\nPeak: Ksh. 100\nOffPeak: Ksh. 70', 'Location': '\nKhoja Stage',
     'Latitude': -1.281305, 'Longitude': 36.822566},
    {'Name': 'Buruburu 58 Sacco', 'Destination': '\nCity Stadium, Uchumi, Jogoo Road, Buruburu',
     'Fare': '\nPeak: Ksh. 80\nOffPeak: Ksh. 50',
     'Location': '\nTom Mboya Street\nOpposite Archives', 'Latitude': -1.284397, 'Longitude': 36.826094},
    {'Name': 'Chelsea Trans', 'Destination': '\nThika Road, Zimmerman, \nGithurai 44, Kahawa West', 'Fare': '\nKsh. 50',
     'Location': '\nTom Mboya Street', 'Latitude': -1.282375, 'Longitude': 36.823425},
    {'Name': 'City Hoppa', 'Destination': '\nRT 1, \nKMTC, Mbagathi, Ngumo, \nRT 2, \nUpper Hill, KNH, KMTC, '
                                          '\nRT 3, \nNgong Road, Uchumi, \nCommunity, Posta, Kabiria',
     'Fare': '\nRT 1: \nRT 2: \nRT 3:',
     'Location': '\nCity Hallway\nNext to Kencom House\nOpposite Hilton Hotel', 'Latitude': -1.2853783, 'Longitude': 36.8253238},
    {'Name': 'City Shuttle', 'Destination': '\n',
     'Fare': '\n',
     'Location': '\nTom Mboya Street\nNext to Tuskys Supermarket', 'Latitude': -1.284251, 'Longitude': 36.825925},
    {'Name': 'City Shuttle', 'Destination': '\nNTSA, Britam, Kasneb, \nKNH, Yaya, Amboseli, Kawangware', 'Fare': '',
     'Location': '\nCity Hallway\nNear Kencom House\nOpposite Hilton Hotel', 'Latitude': -1.2858483,
     'Longitude': 36.8245},
    {'Name': 'City Shuttle | Metro Trans', 'Destination': '\nWaiyaki Way, Uthiru, Waithaka, \nDagoretti Mkt, Ndunyu',
     'Fare': '',
     'Location': '\nTom Mboya Street\nNext to Tuskys', 'Latitude': -1.283876, 'Longitude': 36.825492},
    {'Name': 'City Shuttle Premium', 'Destination': '\nKangemi, Kinoo, Regen, Kikuyu', 'Fare': '\n',
     'Location': '\nTom Mboya Street\nNext to Njengi House\nOpposite Quickmart', 'Latitude': -1.283786,
     'Longitude': 36.825148},
    {'Name': 'Classic Shuttle', 'Destination': '\n', 'Fare': '\n', 'Location': '\n', 'Latitude': -1.283642,
     'Longitude': 36.826453},
    {'Name': 'Classic Luxury Shuttle', 'Destination': '\n', 'Fare': '\n', 'Location': '\n', 'Latitude': -1.283314,
     'Longitude': 36.826517},
    {'Name': 'COSY Limited', 'Destination': '\nWestlands, Kabete, Ndumboini', 'Fare': '\n',
     'Location': '\nLatema Road\nNext to Odeon Cinema', 'Latitude': -1.282924, 'Longitude': 36.825038},
    {'Name': 'Crossland | Crossroad Shuttle',
     'Destination': '\nRT 1, \nNakuru\nRT 2, \nKakamega, Kapsabet',
     'Fare': '\n',
     'Location': '\nDubois Road\nJust off Latema Rd',
     'Latitude': -1.282105, 'Longitude': 36.825748},
    {'Name': 'Digital Luxury Shuttle', 'Destination': '\nWestlands, Kangemi, Uthiru, Kinoo, Kikuyu', 'Fare': '\n',
     'Location': '\nLatema Road\nNext to Odeon Cinema', 'Latitude': -1.283098, 'Longitude': 36.824943},
    {'Name': 'Eastleigh Circular | (Eastleigh)', 'Destination': '\nFig Tree, Pangani, Mlango, Eastleigh, Garissa',
     'Fare': '\nPeak: Ksh. 70\nOffPeak Ksh. 50',
     'Location': '\nTom Mboya Street\nOpposite Tuskys Supermarket\nNear Super Metro',
     'Latitude': -1.283923, 'Longitude': 36.825296},
    {'Name': 'Eastleigh Circular | Nicech Classic',
     'Destination': '\nFig Tree, Pangani, Mlango, Eastleigh, Garissa', 'Fare': '\nPeak: Ksh. 70\nOffPeak Ksh. 50',
     'Location': '\nEnd of Tom Mboya Street\nKhoja Stage',
     'Latitude': -1.281760, 'Longitude': 36.822637},
    {'Name': 'Embassava Sacco', 'Destination': '\nMombasa Road, Embakasi',
     'Fare': '\nPeak: Ksh. 80-100\nOffPeak: Ksh. 50',
     'Location': '\nAccra Rd\nOpposite Tuskys Supermarket', 'Latitude': -1.284181,
     'Longitude': 36.826224},
    {'Name': 'Embassava Sacco', 'Destination': '\nJogoo Road, Embakasi',
     'Fare': '\nPeak: Ksh. 80-100\nOffPeak: Ksh. 50',
     'Location': '\nAccra Rd\nopposite Tuskys Supermarket', 'Latitude': -1.284048,
     'Longitude': 36.826393},
    {'Name': 'Enebled Shuttle', 'Destination': '\nWestlands, Uthiru, Kangemi,Kabete, Kikuyu',
     'Fare': '\nPeak: Ksh. 100\nOffPeak: Ksh. 50',
     'Location': '\nTom Mboya Street-Tom Mboya Walk Junction', 'Latitude': -1.285299, 'Longitude': 36.826279},
    {'Name': 'Ennus Limited', 'Destination': '\nFlyover, Njambini,Ol Kalou, Nyahururu', 'Fare': '\n',
     'Location': '\nKhoja Stage', 'Latitude': -1.281147, 'Longitude': 36.822946},
    {'Name': 'Expresso Limited', 'Destination': '\nNgara, Roysambu, Seasons, \nKasarani, Mwiki',
     'Fare': '\nPeak: Ksh. 70\nOffPeak Ksh. 60',
     'Location': '\nTom Mboya Street\nNext to Imenti House\nOpposite Platinum Plaza', 'Latitude': -1.282931,
     'Longitude': 36.824100},
    {'Name': 'Expresso Limited', 'Destination': '', 'Fare': '', 'Location': '', 'Latitude': -1.284707,
     'Longitude': 36.825991},
    {'Name': 'Ganaki Sacco', 'Destination': '\nNgara, Muthaiga, Junction, \nHospital Hill, Gichagi, Karura',
     'Fare': '\n',
     'Location': '\nTom Mboya Street\nNear Fire Station', 'Latitude': -1.282155, 'Longitude': 36.823549},
    {'Name': 'Ganaki Sacco', 'Destination': '\nNgara, Muthaiga, Junction, \nHospital Hill, Gichagi, Karura',
     'Fare': '\n',
     'Location': '\nLagos Road\nNear Marble Arch Hotel', 'Latitude': -1.281955, 'Longitude': 36.823839},
    {'Name': 'Hannover Swift', 'Destination': '\nNgara, Allsops, Seasons, Mwiki',
     'Fare': '\nPeak: Ksh. 100\nOffPeak: Ksh. 70',
     'Location': '\nTom Mboya Street\nNear Imenti House', 'Latitude': -1.283112, 'Longitude': 36.824307},
    {'Name': 'Home Sacco', 'Destination': '\nWestgate, Wangingi, Pepon Rd, Gathiga',
     'Fare': '\nPeak: Ksh. 70\nOffPeak Ksh. 50',
     'Location': '\nKhoja Stage', 'Latitude': -1.281225, 'Longitude': 36.822490},
    {'Name': 'Huruma 46 Sacco', 'Destination': '\nJuja Road, Rounda, Huruma',
     'Fare': '\nPeak: Ksh. 70\nOffPeak: Ksh. 50',
     'Location': '\nTom Mboya Street\nNear Best Lady',
     'Latitude': -1.282290, 'Longitude': 36.823527},
    {'Name': 'Imani Shuttle | Neno Sacco', 'Destination': '\nVoi-Mombasa', 'Fare': '\n', 'Location': '\n',
     'Latitude': -1.282439, 'Longitude': 36.827163},
    {'Name': 'Jonsaga Sacco', 'Destination': '\nJuja Road, Rounda, Huruma', 'Fare': '\n',
     'Location': '\nTom Mboya Street\nNear Best Lady', 'Latitude': -1.282350, 'Longitude': 36.823592},
    {'Name': 'Kacose Sacco | Unimax Classic | Bahima Sacco', 'Destination': '\nLimuru Road, Village Mkt, Runda, \nTwo Rivers, Banana, '
                                                             'Muchatha',
     'Fare': '\nPeak: Ksh. 100\nOffPeak: Ksh. 70',
     'Location': '\nKhoja Stage', 'Latitude': -1.281486, 'Longitude': 36.822720},
    {'Name': 'Kasa Trans', 'Destination': '\nRoysambu, Kasarani, Mwiki', 'Fare': '\n',
     'Location': '\nTom Mboya Street\nNext to Mega Centre Exhibition\nOpposite Odeon Cinema',
     'Latitude': -1.283311, 'Longitude': 36.824381},
    {'Name': 'KBS Limited',
     'Destination': '\nKMTC, Mbagathi, Kenyatta Mkt, Ngumo, \nYaya, Amboseli, Kasneb, Mediheal, Kawangware',
     'Fare': '\n',
     'Location': '\nCity Hallway\nNext to Kencom House', 'Latitude': -1.2855761, 'Longitude': 36.8251387},
    {'Name': 'Kettno Sacco', 'Destination': '\nMwea, Embu, Siakago',
     'Fare': '\nEmbu\nPeak: Ksh. 700\nOffPeak: Ksh. 450\n\nSiakago\nPeak: 800\nOffPeak:Ksh. 550',
     'Location': '\nAccra Road\nNext to Accra Trade Centre', 'Latitude': -1.282988,
     'Longitude': 36.827062},
    {'Name': 'Kettno Shuttles', 'Destination': '', 'Fare': '', 'Location': '', 'Latitude': -1.282823,
     'Longitude': 36.827095},
    {'Name': 'Kijabe Line', 'Destination': '\n',
     'Fare': '\n',
     'Location': '\nKhoja Stage',
     'Latitude': -1.281404, 'Longitude': 36.822882},
    {'Name': 'Killeton Sacco',
     'Destination': '\nRT 1, \nChiromo,  Kawangware, Riverside, \nRT 2, \nTwo Rivers, Ruaka, Ndenderu, Kiambu Rd',
     'Fare': '\nPeak: Ksh. 100\nOffPeak: Ksh. 80',
     'Location': '\nLatema Road\nOpposite Green Court Hotel', 'Latitude': -1.282399, 'Longitude': 36.825297},
    {'Name': 'Kirinyaga Shuttle | Supreme Shuttle', 'Destination': '\nNakuru, Kerugoya',
     'Fare': '\nKirinyaga Shuttle\nKerugoya: Ksh.\nNakuru: Ksh. \n\nSupreme Shuttle\nKerugoya: Ksh.\nNakuru: Ksh.',
     'Location': '\nAccra Road\nNear Emmacra Building', 'Latitude': -1.283205,
     'Longitude': 36.826851},
    {'Name': 'KMO Sacco', 'Destination': '\nNaivas, Westlands, Safaricom, Kangemi', 'Fare': '\n',
     'Location': '\nKhoja Stage', 'Latitude': -1.281583, 'Longitude': 36.822391},
    {'Name': 'KMO Sacco', 'Destination': '\nWestlands, Kangemi, Uthiru, \nDagoretti Mkt, 87 Junction, Kinoo, Kikuyu',
     'Fare': '\n',
     'Location': '\nLatema Rd\nNext to Odeon Cinema', 'Latitude': -1.283222, 'Longitude': 36.824813},
    {'Name': 'Latema Travels', 'Destination': '\nWestlands, Kabete, Ndumboini', 'Fare': '\n',
     'Location': '\nLagos Road\nNear Marble Arch Hotel', 'Latitude': -1.282059, 'Longitude': 36.824795},
    {'Name': 'Latema Travels', 'Destination': '\nNgong Road, Kenyatta Road, Kabiria', 'Fare': '\n',
     'Location': '\nTom Mboya Walk\nBetween Ambassador and Archives', 'Latitude': -1.285211,
     'Longitude': 36.825950},
    {'Name': 'Latema Travels', 'Destination': '\nThika Road, Roysambu, Juja, Thika',
     'Fare': '\nPeak: Ksh. 80\nOffPeak: Ksh. 50',
     'Location': '\nTom Mboya Street\nBehind Archives\nNext to Lizaya Training Institute', 'Latitude': -1.284254,
     'Longitude': 36.825707},
    {'Name': 'LBD T Ltd', 'Destination': '\n',
     'Fare': '\n',
     'Location': '\nBehind Platinum Plaza\nNear Shell Petrol Station',
     'Latitude': -1.282724, 'Longitude': 36.82452},
    {'Name': 'Likana Sacco',
     'Destination': '\nRT 1, \nLimuru, Nakuru, \nRT 2, \nRuaka, Ndenderu, Posta, Kabuku, Ngecha,'
                    ' \nRT 3, \nKinoo, Gitaru, Zambezi, Nderi',
     'Fare': '\n',
     'Location': '\nKhoja Stage', 'Latitude': -1.280839, 'Longitude': 36.822636},
    {'Name': 'Lina Sacco', 'Destination': '\nLimuru, Ruaka, Nakuru', 'Fare': '\n',
     'Location': '\nKhoja Stage', 'Latitude': -1.280920, 'Longitude': 36.822565},
    {'Name': 'Lopha Sacco', 'Destination': '\nStima Plaza, Agakhan, Highridge, Parklands', 'Fare': '\n',
     'Location': '\nKhoja Stage\nNear Old Nation House', 'Latitude': -1.281640, 'Longitude': 36.822501},
    {'Name': 'Lopha Sacco', 'Destination': '\nRT 1, \nHighridge, Agakhan, Stima Plaza, \nKwa Chief Mwisho'
                                           '\nRT 2, Ngara, K.I.E, Pangani', 'Fare': '\n',
     'Location': '\nLatema Rd\nNear Odeon Cinema\nNext to Shell Petrol Station', 'Latitude': -1.282690,
     'Longitude': 36.825063},
    {'Name': 'Lopha Travels | (James Gichuru)', 'Destination': '\nAvenue Hospital, Oshwal Academy, '
     '\nUK, Westgate, James Gichuru', 'Fare': '\n',
     'Location': '\nLatema Rd\nNear Odeon Cinema\nNext to Shell Petrol Station', 'Latitude': -1.2828308,
     'Longitude': 36.8249220},
    {'Name': 'Lopha Travels | (Ruaka)', 'Destination': '\nRuaka', 'Fare': '\nPeak: Ksh. 100\nOffPeak: Ksh. 60',
     'Location': '\nLatema Road\nOpposite Shell Petrol Stn',
     'Latitude': -1.282509, 'Longitude': 36.825278},
    {'Name': 'Lopha Travels | (Thika Rd)', 'Destination': '\nThika Road, Roysambu, Githurai 45, \nRuiru, Juja', 'Fare': '\n',
     'Location': '\nLatema Road\nOpposite Odeon Cinema', 'Latitude': -1.282434, 'Longitude': 36.825339},
    {'Name': 'Lopha Travels | (Matangi)',
     'Destination': '\nRoysambu, Githurai 45, Kimbo, \nMatangi, (off Thika Rd at Kimbo)', 'Fare': '\n',
     'Location': '\nLatema Road\nOpposite Odeon Cinema', 'Latitude': -1.282775, 'Longitude': 36.825055},
    {'Name': 'Lopha Travels | (Ruiru Ndani)', 'Destination': '\nThika Road, Roysambu, Githurai 45, '
     '\nRuiru Ndani, Kwa Kairu)', 'Fare': '\n',
     'Location': '\nLatema Road\nOpposite Odeon Cinema\nBesides Tom Mboya Street', 'Latitude': -1.283139,
     'Longitude': 36.824740},
    {'Name': 'Lucky BD', 'Destination': '\nAllsops, Outer-Ring Road, \nBaba Dogo, Lucky Summer', 'Fare': '\n',
     'Location': '\nOff Tom Mboya Street\nBetween Platinum Plaza&Dominion Building', 'Latitude': -1.2827887,
     'Longitude': 36.8242924},
    {'Name': 'Lucky Trans', 'Destination': '\nWestlands, Banana', 'Fare': '\n',
     'Location': '\nKhoja Stage', 'Latitude': -1.281379, 'Longitude': 36.822653},
    {'Name': 'MANMO Sacco',
     'Destination': '\nSurvey, Utalii, Allsops, Area 4, \nStage 29/30, Mathare North',
     'Fare': '\nPeak: Ksh. 80\nOffPeak: Ksh. 50',
     'Location': '\nTom Mboya Street\nNext to Platinum Plaza', 'Latitude': -1.282844, 'Longitude': 36.824219},
    {'Name': 'Mark One Shuttle', 'Destination': '\nChuka, Meru',
     'Fare': '(10-Seater)\nPeak: Ksh. 1500\nOffPeak: Ksh. 1000', 'Location': '\nTsavo Road, just off Accra Road',
     'Latitude': -1.283356, 'Longitude': 36.826575},
    {'Name': 'Menany Sacco | Menya Sacco | Maua Shuttle | Maua Shark',
     'Destination': '\nChuka, Meru, \nNakuru, Isiolo, Meru, Mombasa, (Menany ONLY)',
     'Fare': '\nChuka, Meru\nPeak: Ksh. 1200-1500\nOffPeak: Ksh. 1000\n\nMenany Sacco Routes\n',
     'Location': '\nAccra Road-Tsavo Road Junction', 'Latitude': -1.283418, 'Longitude': 36.826691},
    {'Name': 'Metro Trans | (Westlands-Kikuyu)', 'Destination': '\nWestlands, Kabete, Kangemi, Uthiru, '
                                                                '\nGitaru, Regen, Kikuyu',
     'Fare': '\n',
     'Location': '\nTom Mboya Street\nOpposite Space International\nNext to Lazaru`s Restaurant',
     'Latitude': -1.283681, 'Longitude': 36.825006},
    {'Name': 'Metro Trans | (Kasarani-Maji Mazuri)', 'Destination': '\nFig Tree, Allsops, Roysambu, '
     '\nKasarani, Mwiki, Maji Mazuri', 'Fare': '\nPeak: Ksh. 70\nOffPeak Ksh. 60',
     'Location': '\nTom Mboya Street\nNext to Imenti House\nOpposite Platinum Plaza', 'Latitude': -1.283002,
     'Longitude': 36.824209},
    {'Name': 'Metro Trans | (Zambezi-Kahuho)', 'Destination': '\nZambezi, Kamuguga, Kahuho', 'Fare': '\n',
     'Location': '\nKhoja Stage', 'Latitude': -1.2808413, 'Longitude': 36.8227918},
    {'Name': 'Meru Shuttle Company', 'Destination': '\nMeru', 'Fare': '\nPeak: Ksh. 1200-1500\nOffPeak: Ksh. 1000',
     'Location': '\nAccra Road-Tsavo Road Junction', 'Latitude': -1.283524,
     'Longitude': 36.826548},
    {'Name': 'Mololine Shuttle', 'Destination': '\nNakuru, Kisumu, Busia',
     'Fare': '\nNakuru: \nPeak: Ksh. 1000, Offpeak: Ksh. 600\n\nKisumu\nPeak: ,OffPeak: \n\nBusia\nPeak: ,OffPeak: ',
     'Location': '\nLatema Road\nEmbassy Cinema Building', 'Latitude': -1.282434, 'Longitude': 36.825412},
    {'Name': 'Mololine Shuttle', 'Destination': '\n',
     'Fare': '\n',
     'Location': '\nLatema Road',
     'Latitude': -1.282230, 'Longitude': 36.825533},
    {'Name': 'MSL Operators', 'Destination': '\nThika Road, Survey, Allsops, Roysambu, \nMaji Mazuri, Kasarani, Mwiki',
     'Fare': '\nKsh. 60',
     'Location': '\nTom Mboya Street\nNext to Beba Beba building', 'Latitude': -1.282707, 'Longitude': 36.823816},
    {'Name': 'Namuga Sacco', 'Destination': '\nRT 1, Thika Road, Juja, Thika\nRT 2, Murang`a, Gakindu, Nyeri',
     'Fare': '\n',
     'Location': '\nAlong Latema Rd\nOpposite Fallon Bookshop', 'Latitude': -1.282063, 'Longitude': 36.825553},
    {'Name': 'Nanyuki Express Cab Services', 'Destination': '\nNanyuki, Nyeri, Karatina',
     'Fare': '\nNanyuki: Ksh. 600\nNyeri: Ksh. 450\nKaratina: Ksh. 400',
     'Location': '\nAccra Road\nNear Raiciri House', 'Latitude': -1.283635,
     'Longitude': 36.826558},
    {'Name': 'Nawaku Sacco',
     'Destination': '\nRT 1, \nGithurai 45, Kahawa Sukari, KU, Bypass\nRT 2, \nSukari Ndani, Felma, Mwihoko',
     'Fare': '\n',
     'Location': '\nBehind Platinum Plaza\nNext to Msikiti',
     'Latitude': -1.282709, 'Longitude': 36.824604},
    {'Name': 'Nawasuku Sacco', 'Destination': '\nThika Road, KU, Ruiru', 'Fare': '\n',
     'Location': '\nBehind Platinum Plaza', 'Latitude': -1.282575, 'Longitude': 36.824307},
    {'Name': 'Nazigi Sacco', 'Destination': '\nThika Road, Zimmerman, Githurai 44, \nKahawa West, KU Referral',
     'Fare': '\nPeak: Ksh. 80\nOffPeak: Ksh. 50',
     'Location': '\nLatema Road\nNext to Shell Petrol Station', 'Latitude': -1.2826512, 'Longitude': 36.8247716},
    {'Name': 'Nazigi Sacco', 'Destination': '\nRoute 44', 'Fare': '\nPeak: Ksh. 80\nOffPeak: Ksh. 50',
     'Location': '\nBehind Platinum Plaza\nNear Shell Petrol Stn', 'Latitude': -1.282773, 'Longitude': 36.824593},
    {'Name': 'Neno Nissan Sacco', 'Destination': '\n', 'Fare': '\n', 'Location': '\n', 'Latitude': -1.282687,
     'Longitude': 36.827174},
    {'Name': 'Neno  Sacco', 'Destination': '\n', 'Fare': '\n', 'Location': '\n', 'Latitude': -1.282628,
     'Longitude': 36.827131},
    {'Name': 'Nicech Classic Eastleigh', 'Destination': '\nFig Tree, Mlango, Eastleigh, Garissa',
     'Fare': '\nPeak: Ksh. 70\nOffPeak Ksh. 50',
     'Location': '\nTom Mboya Street\nOpposite Fire Station', 'Latitude': -1.282036,
     'Longitude': 36.823000},
    {'Name': 'NNK Shuttle | (Westlands-Kikuyu)', 'Destination': '\nWestlands, Regen, Uthiru, Muthiga, \nGitaru Kangemi, Kinoo, Kikuyu',
     'Fare': '\nPeak: Ksh. 100\nOffPeak: Ksh. 50',
     'Location': '\nTom Mboya Street\nOpposite Odeon Cinema\nNext to Ajode Dishes', 'Latitude': -1.283463,
     'Longitude': 36.824747},
    {'Name': 'NNK Shuttle | (Westlands-Kikuyu)', 'Destination': '\nWestlands, Regen, Uthiru, Muthiga, \nGitaru Kangemi, Kinoo, Kikuyu',
     'Fare': '\nPeak: Ksh. 100\nOffPeak: Ksh. 50',
     'Location': '\nTom Mboya Street\nNext to Archives', 'Latitude': -1.284950, 'Longitude': 36.826114},
    {'Name': 'Nyena Shuttle', 'Destination': '\nNyeri, Nakuru', 'Fare': '\nNyeri: Ksh: 450\nNakuru: Ksh. 500',
     'Location': '\nAccra Road\nOpposite White Angle House', 'Latitude': -1.283564,
     'Longitude': 36.826745},
    {'Name': 'Nyakati Sacco', 'Destination': '\nNanyuki, Nyeri, Isiolo, Karatina, Nakuru',
     'Fare': '\nNanyuki: Ksh. 600\nNyeri: Ksh. 450\nIsiolo: Ksh. 600\nKaratina: Ksh. 400\nNakuru: Ksh. 500',
     'Location': '\nAccra Road\nOpposite Al-Noor Exhibitions', 'Latitude': -1.283701,
     'Longitude': 36.826645},
    {'Name': 'Prestige Shuttle', 'Destination': '\nNakuru', 'Fare': '\nNakuru\nKsh. 700',
     'Location': '\nTsavo Road\nJust off Latema Road',
     'Latitude': -1.282603, 'Longitude': 36.825455},
    {'Name': 'Prestige Shuttle', 'Destination': '\nBusia, Kisumu', 'Fare': '\nBusia\nKsh. 1800\n'
                                                                           '\nKisumu\nKsh. 1400',
     'Location': '\nTsavo Road\nJust off Latema Road',
     'Latitude': -1.282737, 'Longitude': 36.825530},
    {'Name': 'Raha Express', 'Destination': '\nMeru, Isiolo', 'Fare': '\nPeak: Ksh. 1200\nOffPeak: Ksh. 1000',
     'Location': '\nAccra Road\nNext to Nyota Building', 'Latitude': -1.282960,
     'Longitude': 36.827029},
    {'Name': 'Royal Swift', 'Destination': '\nJogoo Road, Embakasi', 'Fare': '\nPeak: Ksh. 80\nOffPeak: Ksh. 50',
     'Location': '\nTom Mboya Street\nNear Family Bank', 'Latitude': -1.282344,
     'Longitude': 36.8234248},
    {'Name': 'Runka Sacco',
     'Destination': '\nRT 1, Thika Road, Thika, Weitethie, Juja, \nRT 2, Limuru Road, Number 8, Wangige'
                    '\nRT 3, Kiambu Road, Muthaiga, DCI, \nBypass, Githogoro',
     'Fare': '\nRT 1: \nPeak: Ksh. 100, OffPeak: Ksh. 60\nRT 2: \nPeak: Ksh. 80, OffPeak: Ksh. 60\nRT 3: \nPeak: Ksh, '
             'Offpeak: Ksh. ',
     'Location': '\nLatema Road\nOpposite Savani`s Book Centre', 'Latitude': -1.282192, 'Longitude': 36.825468},
    {'Name': 'Runka Sacco', 'Destination': '\n',
     'Fare': '\n',
     'Location': '\n',
     'Latitude': -1.282074, 'Longitude': 36.825483},
    {'Name': 'Safari Prestige', 'Destination': '\nKericho, Kisumu', 'Fare': '\nKericho: Ksh. 1300\nKisumu: Ksh. 1400',
     'Location': '\nTsavo Road\nNear Igoji House', 'Latitude': -1.283301,
     'Longitude': 36.826416},
    {'Name': 'Satima Sacco',
     'Destination': '\nRT 1, \nFlyover, Njambini, Ol` Kalou, Nyahururu\n '
                    'RT 2, \nNyambiri, Kimende, Kijabe, Ol` Kalou Express',
     'Fare': '\n',
     'Location': '\nKhoja Stage', 'Latitude': -1.281057, 'Longitude': 36.822953},
    {'Name': 'Stage Shuttle', 'Destination': '\nKaratina, Nyeri, Nakuru',
     'Fare': '\nKaratina: Ksh. 400\nNyeri: Ksh. 450\nNakuru: Ksh. 500',
     'Location': '\nAccra Road\nNear Emmacra Building', 'Latitude': -1.283286,
     'Longitude': 36.826933},
    {'Name': 'Star Bus', 'Destination': '\nWestlands, Kabete, Uthiru', 'Fare': '\n',
     'Location': '\nLatema Rd-Lagos Rd Junction\nNear Lois Plaza', 'Latitude': -1.282013, 'Longitude': 36.825314},
    {'Name': 'Super Metro | (Ngong Road)', 'Destination': '\nNgong Road, CBD, JKIA', 'Fare': '\n',
     'Location': '\nGovernment Lane\nNear Kenya National Archives\nOff Maragua Ln',
     'Latitude': -1.284201593269007, 'Longitude': 36.82514364495415},
    {'Name': 'Super Metro | (Thika Road)',
     'Destination': '\nRT 1, \nThika Road, Roysambu, Ruiru, \nKenyatta Road, Juja, \n'
                    'RT 2, \nThika Road, Ruiru, Juja, Juja Farm, \nRT 3, \nThika Road, Thika, Makongeni',
     'Fare': '\nPeak: Ksh. 100\nOffPeak: Ksh. 60',
     'Location': '\nMaragua Lane\nNear Kenya National Archives',
     'Latitude': -1.284416666666667, 'Longitude': 36.82512143526326},
    {'Name': 'Super Metro', 'Destination': '\n', 'Fare': '\n',
     'Location': '\n', 'Latitude': -1.284104711068739, 'Longitude': 36.82538113863239},
    {'Name': 'Super Metro', 'Destination': '\nWestlands, Kinoo, Kangemi, Kikuyu', 'Fare': '\n',
     'Location': '\nEnd of Maragua Lane\next to Tom Mboya Street\nNear Kenya National Archives',
     'Latitude': -1.284265723054538, 'Longitude': 36.82525073164653},
    {'Name': 'Super Tram', 'Destination': '\nRoute 44',
     'Fare': '\nPeak: Ksh. 70\nOffPeak Ksh. 50',
     'Location': '\n',
     'Latitude': -1.282572, 'Longitude': 36.823660},
    {'Name': 'Supreme Shuttle | Nyena Sacco', 'Destination': '\nNakuru, Naivasha, Gilgil, Karatina, Eldoret, Nanyuki',
     'Fare': '\nNyena Sacco\nNakuru: Ksh. 500, Naivasha/Gilgil: Ksh. 500\nNanyuki: Ksh.\n'
             'Karatina: Ksh. 400, Eldoret: Ksh. 1000-1500\n\nSupreme Shuttle\nNakuru: Ksh. 500, Naivasha/Gilgil: Ksh. '
             '500\nKaratina: Ksh. 400, Eldoret: Ksh. 1000-1500',
     'Location': '\nAccra Road\nNear Emmacra Building',
     'Latitude': -1.283321, 'Longitude': 36.826790},
    {'Name': 'Transworld Sacco', 'Destination': '\nMP.SHH, Parklands, Westlands', 'Fare': '\n',
     'Location': '\nKhoja Stage', 'Latitude': -1.281305, 'Longitude': 36.822566},
    {'Name': 'Tripple S', 'Destination': '\nMuthaiga, Karura, Kasarani, \nKwang`ethe, Kiambu Town', 'Fare': '\n',
     'Location': '\nTom Mboya Street\nNext to Cooperative Bank', 'Latitude': -1.283621, 'Longitude': 36.825204},
    {'Name': 'Trooper Shuttle', 'Destination': '\nWestlands, Muthithi, Kingero, Wangige', 'Fare': '\n',
     'Location': '\nKhoja Stage', 'Latitude': -1.281714, 'Longitude': 36.8224967},
    {'Name': 'Tulaga Nissan', 'Destination': '\nKimende, Flyover, Njambini, \nOl` Kalou, Nyahururu', 'Fare': '\n',
     'Location': '\nKhoja Stage', 'Latitude': -1.280973, 'Longitude': 36.822950},
    {'Name': 'Ungwana Sacco', 'Destination': '\nTharaka Uni, Meru', 'Fare': 'Peak: Ksh. 1000\nOffPeak Ksh. 900',
     'Location': '\nAccra Road\nNear Nyota Building', 'Latitude': -1.283309,
     'Longitude': 36.826710},
    {'Name': 'Unified Poa', 'Destination': '\nSurvey, Allsops, Roasters, \nHomeland, Roysambu, Githurai 45',
     'Fare': '\n',
     'Location': '\nTom Mboya Street\nNext to Mega Centre Exhibition\nOpposite Odeon Cinema',
     'Latitude': -1.283277, 'Longitude': 36.824510},
    {'Name': 'Walokana Sacco', 'Destination': '\nMwimuto, Wangige, Westlands, \nGathiga, Kabete',
     'Fare': '\nPeak: Ksh. 100\nOffPeak: Ksh. 70',
     'Location': '\nKhoja Stage', 'Latitude': -1.281379, 'Longitude': 36.822653},
    {'Name': 'Walokana Sacco', 'Destination': '\nWestgate, Pepon Rd, Gathiga',
     'Fare': '\nPeak: Ksh. 100\nOffPeak: Ksh. 70',
     'Location': '\nKhoja Stage', 'Latitude': -1.281305, 'Longitude': 36.822566},
    {'Name': 'Zuri Genesis | (Thika Road-Ruiru)', 'Destination': '\nThika Road, Roysambu, Bypass, \nKwa Kairu, Ruiru',
     'Fare': '\nPeak: Ksh. 80\nOffPeak: Ksh. 50',
     'Location': '\nTom Mboya Street\nNext to Odeon Cinema', 'Latitude': -1.283337, 'Longitude': 36.824837},
    {'Name': 'Zuri Genesis | (Thika RD-Roysambu-Kahawa West',
     'Destination': '\nThika Road, Roysambu, Zimmerman, \nMirema, Githurai 44, Kahawa West '
                    '\n(Zuri operates in Kahawa West in the morning ONLY)',
     'Fare': '\nPeak: Ksh. 80\nOffPeak: Ksh. 50',
     'Location': '\nTom Mboya Street\nNear Star Mall\nOpposite Bestlady', 'Latitude': -1.282514,
     'Longitude': 36.823596},
    {'Name': 'Zuri Genesis', 'Destination': '\n',
     'Fare': '\n',
     'Location': '\nTom Mboya Street\nNear Fire Station',
     'Latitude': -1.282286, 'Longitude': 36.823298},

]
